### ISSUE TITLE
[FEATURES]Support fuse clean policy for JindoRuntime. 

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#1254]
**What feature you'd like to add:**
Support fuse clean policy for JindoRuntime. 

Fluid adopts fuse lazy start since v0.7.0. This PR supports two different fuse clean policy for JindoRuntime: `OnDemand` and `OnRuntimeDeleted`. `OnDemand` is the default clean policy and it cleans fuse pods whenever the fuse pod on some node is not in use, while with the `OnRuntimeDeleted` policy, once a fuse pod is lazily created, it will never be cleaned until the cache runtime is deleted. 

`OnDemand` is useful for saving cluster resources, while `OnRuntimeDeleted` is useful for avoiding frequent restarting.

User can specify the fuse clean policy by setting it in JindoRuntime:
```
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: hadoop
spec:
  ...
  fuse:
    # cleanPolicy: OnDemand
    cleanPolicy: OnRuntimeDeleted
```

**Why is this feature needed:**
