### ISSUE TITLE
[BUG] No data is cached in JindoFS after a DataLoad completes 

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#1460]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid version: 808c72e
Jindo version: registry.cn-shanghai.aliyuncs.com/jindofs/smartdata:3.8.0

**Describe the bug**
When I created a DataLoad to cache data from OSS into Jindo, I found no data is actually cached after the DataLoad completes.

Before DataLoad:
```
NAME         UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
oss-bucket   2.97GiB          0.00B    20.00GiB         0.0%                Bound   3m6s
```

After DataLoad, Jindo remains empty
```
NAME         UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
oss-bucket   2.97GiB          0.00B    20.00GiB         0.0%                Bound   8m56s
```

The log for DataLoad:
[dataload.log](https://github.com/fluid-cloudnative/fluid/files/8125383/dataload.log)

One strange thing I found in DataLoad log is that it finishes only with little time for caching a 2.5GB dataset:
```
2022-02-23 15:11:57,965 INFO common.FsStats: cmd=metaSync, src=jfs://jindo/spark, dst=null, size=0, parameter=, time-in-ms=2004, version=3.7.3
Successfully load metadata for jfs://jindo/spark, recursive true
15:11:57.967076 209 clCacheCacheFileletCall.cpp:44] Async data cache commond received for path jfs://jindo/spark, will send to namespace
2022-02-23 15:11:57,969 INFO common.FsStats: cmd=cache, src=jfs://jindo/spark, dst=null, size=0, parameter=, time-in-ms=3, version=3.7.3
Successfully load data for jfs://jindo/spark

real    0m3.479s
user    0m1.929s
sys     0m0.176s
```

**What you expect to happen:**
the `jfs://jindo/spark` data should be cached into Jindo.

**How to reproduce it**
1. dataset.yaml
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: oss-bucket
spec:
  mounts:
    - mountPoint: oss://<some_bucket>/
      options:
        fs.oss.endpoint: <ENDPOINT>
      name: ossbucket
      encryptOptions:
        - name: fs.oss.accessKeyId
          valueFrom:
            secretKeyRef:
              name: tzsecret
              key: fs.oss.accessKeyId
        - name: fs.oss.accessKeySecret
          valueFrom:
            secretKeyRef:
              name: tzsecret
              key: fs.oss.accessKeySecret
---
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: oss-bucket
spec:
  replicas: 2
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10G
        high: "0.99"
        low: "0.98"
```

2. dataload.yaml
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: oss-dataload
spec:
  loadMetadata: true
  dataset:
    name: oss-bucket
    namespace: default
```

3. Check the cache status after dataload completes

**Additional Information**

**Comment by cheyang** [comment]
@TrafalgarZZZ Can this issue be closed?

**Comment by TrafalgarZZZ** [comment]
Found the problem. When using DataLoad with JindoFS, `loadMetadata: true` is a necessary property to make it work well.

```
apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: oss-dataload
spec:
  dataset:
    name: oss-bucket
    namespace: default
  loadMetadata: true
```
