### ISSUE TITLE
[BUG] alluxio runtime to run with non-root user  has no permission to cache data

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#174]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

1. Create alluxio runtime

```
spec:
  replicas: 2
#  alluxioVersion:
#    image: registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio
#    imageTag: "2.3.0-SNAPSHOT-f83f51e"
#    imagePullPolicy: Always
  initUsers:
    image: registry.cn-hangzhou.aliyuncs.com/fluid/init-users
    imageTag: v0.3.0
    imagePullPolicy: Always
  tieredstore:
    levels:
      - mediumtype: SSD
        path: /var/lib/docker/alluxio
        quota: 2Gi
        high: "0.95"
        low: "0.7"
  runAs:
    uid: 1005
    gid: 1005
    user: myuser
    group: mygroup
```

2. I found the alluxio worker doesn't have permission to create cache directory

```
2020-09-20 09:47:26,568 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker
2020-09-20 09:47:26,644 ERROR StorageTier - Unable to initialize storage directory at /var/lib/docker/alluxio/alluxioworker: Failed to create folder /var/lib/docker/alluxio/alluxioworker
```

3. For now, I have to add permission before creating alluxio runtime in specified node

```
chmod -R 777 /var/lib/docker/alluxio
```

**What you expect to happen:**

I hope we can give the permission 777 to the cache directory ` /var/lib/docker/alluxio`  in the init containers.

**How to reproduce it**

**Additional Information**
