### ISSUE TITLE
[FEATURES]How cache workers are scheduled to computing nodes

### ISSUE THREAD

**Issue by donghucey** [fluid-cloudnative/fluid#2141]
When the computing node does not have a cache worker，Scheduling cache workers to computing nodes can speed up training。Do you have relevant information?

**Comment by TrafalgarZZZ** [comment]
@donghucey you can schedule data cache by specifying node affinity in Dataset.spec. 

For example:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: demo
spec:
  mounts:
    - mountPoint: https://downloads.apache.org/hbase/stable/
      name: demo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: foolabel
              operator: In
              values:
                - "true"
```

Please refer to this [doc](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/data_co_locality.md) for more information
