### ISSUE TITLE
[BUG] Got Invalid argument because of empty space in mount point when starting fuse

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#2181]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
For example, create the dataset with the following spec
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: dataset-mountpoint-with-space
spec:
  mounts:
  - mountPoint: oss://some_bucket/20221012 22:36:02/file
    name: oss
```

Then, the fuse pod failed to start due to invalid argument like:
```
fuse: invalid argument '22:36:02/file'
```

fuse pod spec:
```
containers:
- args:
   - -okernel_cache
   - -ouri=oss://some_bucket/20221012 22:36:02/file
```

This bug can be fixed by quote fuse args like:
```
"-ouri=oss://some_bucket/20221012 22:36:02/file"
```

**What you expect to happen:**
Fuse pod should start successfully

**How to reproduce it**
Follow the steps mentioned above.

**Additional Information**
