### ISSUE TITLE
[BUG] Setting master ports does not take effect for alluxioruntime

### ISSUE THREAD

**Issue by wenfang6** [fluid-cloudnative/fluid#2198]
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid-master
**Describe the bug**
l want to set master ports in alluxioruntime, l only set rpc port, but alluxio starting don‘t use my port 
**What you expect to happen:**
l hope l can set singe port in alluxioruntime for alluxio master. 
e.g.
 ```yml
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  namespace: fluid-wen
  name: wen-test
spec:
  hadoopConfig: wen-testconf
  replicas: 1
  master:
    ports:
      rpc: 19998
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: '0.95'
        low: '0.7'
```

**How to reproduce it**

**Additional Information**
