### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zwwhdls** [fluid-cloudnative/fluid#2201]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
JuiceFS command support [multiple cache-dir with semicolon or colon](https://juicefs.com/docs/zh/community/command_reference). When specify multiple tiredstore in Runtime, it will fail.

```
...
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm1;/dev/shm2
        quota: 40Gi
        low: "0.1"
```

**What you expect to happen:**
Multiple cache dirs are the same level tiredstore in JuiceFS Runtime. They should be all mounted in fuse and worker pod.

**How to reproduce it**

**Additional Information**
