### ISSUE TITLE
[BUG] JuiceFSRuntime - error when credential key is not "secret-key"

### ISSUE THREAD

**Issue by zwwhdls** [fluid-cloudnative/fluid#2508]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
When secret key in dataset is not "secret-key", juicefs runtime will fail.

```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: jfsdemo
spec:
  accessModes:
  - ReadWriteMany
  mounts:
  - encryptOptions:
    - name: metaurl
      valueFrom:
        secretKeyRef:
          key: metaurl
          name: jfs-secret
    - name: access-key
      valueFrom:
        secretKeyRef:
          key: accesskey
          name: jfs-secret
    - name: secret-key
      valueFrom:
        secretKeyRef:
          key: secretkey
          name: jfs-secret
    mountPoint: juicefs:///
    name: juicefs-community
    options:
      bucket: http://minio:9000/minio/test
      storage: minio
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**
