### ISSUE TITLE
[BUG] Failed to override Alluxio's properties in spec.master or spec.worker

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#2521]
**What is your environment(Kubernetes version, Fluid version, etc.)**
6e6294b

**Describe the bug**
In cases that I want to set properties of Alluxio, only properties in `AlluxioRuntime.spec.properties` take effect. The properties set in `AlluxioRuntime.spec.master.properties` or `AlluxioRuntime.spec.worker.properties` are ignored.

For example:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: hbase
spec:
  mounts:
    - mountPoint: https://mirrors.bit.edu.cn/apache/hbase/stable/
      name: hbase
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: hbase
spec:
  replicas: 1
  properties:
    alluxio.worker.block.heartbeat.interval: "30sec"
    alluxio.master.rpc.executor.keepalive: "30sec"
  master:
    properties:
      alluxio.master.rpc.executor.keepalive: "45sec"
      alluxio.master.rpc.executor.max.pool.size: "300"
  worker:
    properties:
      alluxio.worker.block.heartbeat.interval: "60sec"
      alluxio.worker.block.heartbeat.timeout: "1800sec"
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: "0.95"
        low: "0.7"
```

The expected properties should be:
- alluxio.master.rpc.executor.keepalive: "45sec"
- alluxio.master.rpc.executor.max.pool.size: "300"
- alluxio.worker.block.heartbeat.interval: "60sec"
- alluxio.worker.block.heartbeat.timeout: "1800sec"

However, what I got in Alluxio Master Pod by `alluxio getConf` is like:
```
$ alluxio getConf | grep "alluxio.master.rpc.executor"
alluxio.master.rpc.executor.keepalive=30sec
alluxio.master.rpc.executor.max.pool.size=1024
```

```
$ alluxio getConf | grep "alluxio.worker.block"
alluxio.worker.block.heartbeat.interval=30sec
alluxio.worker.block.heartbeat.timeout=1hour
```

**What you expect to happen:**
`AlluxioRuntime.spec.master.properties` and `AlluxioRuntime.spec.worker.properties` should override the properties in AlluxioRuntime.spec.properties.

**How to reproduce it**
Follow the steps mentioned above

**Additional Information**
