### ISSUE TITLE
[BUG] ThinRuntime failed to inherit resources from ThinRuntimeProfile

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#2549]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

Currently, Fluid fails to override resources.requests and resources.limits from ThinRuntimeProfile. For example, when set fuse resources in ThinRuntimeProfile like:
```
kind: ThinRuntimeProfile
...
resources:
   requests:
      cpu: 100m
      memory: 4Gi
```
and set no fuse resources in ThinRuntime, the final fuse pod resources is empty:

```
kind: Pod
resources: {}
```

**What you expect to happen:**
Fuse pod should inherit the resources specification from ThinRuntimeProfile like:
```
kind: Pod
...
resources:
   requests:
      cpu: 100m
      memory: 4Gi
```

**How to reproduce it**
Follow the steps introduced above.

**Additional Information**
