### ISSUE TITLE
[BUG]JindoRuntime fails to parse quota with Mi unit

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#2707]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
Using the following JindoRuntime spec:
```
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: demo-dataset
spec:
  replicas: 2
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 300Mi
        high: "0.99"
        low: "0.99"
```

JindoFS will fail to start with error log messages like:
```
300Mi is not a valid size, Allowed values are like 64, 64k, 64m, 64g, 64mb, 64gb, etc.
```

**What you expect to happen:**

Tieredstore quotas with Mi unit should be supported by JindoRuntime.

**How to reproduce it**
Create JindoRuntime with the above-mentioned spec.

**Additional Information**
