### ISSUE TITLE
[BUG] Allow users to set image info in JindoRuntime

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#2966]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Master branch [3dc5427](https://github.com/fluid-cloudnative/fluid/commit/3dc5427f543ea1ebd58a1a04db1943fc5cc65362)

**Describe the bug**
JindoRuntime now refuses to override global-scoped image info (e.g. image, imageTag, imagePullPolicy).

Users should be allowed to set a different image info in JindoRuntime.spec like this:
```
kind: JindoRuntime
spec:
  jindoVersion:
    image: "myimage"
    imageTag: "mytag"
    imagePullPolicy: "IfNotPresent"
  fuse:
    image: "my-fuse-image"
    imageTag: "my-fuse-tag"
    imagePullPolicy: "Always"
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**
