### ISSUE TITLE
[BUG] Determine if the Alluxio 2.9.0 performance degradation bug affects Fluid

### ISSUE THREAD

**Issue by zhang-x-z** [fluid-cloudnative/fluid#3209]
**What is your environment(Kubernetes version, Fluid version, etc.)**
- K8s version: 1.22.4
- Fluid: 0.9.0
- Alluxio: Both use 2.9.0 and 2.8.1 for testing.

**Describe the bug**
A user finds that in Alluxio 2.9.0 deployed by containers, after loading file in alluxio master, copy file in fuse is very slow (4 minutes). But in Alluxio 2.8.1 it is fast (7 seconds) (for more detail information, check [this issue](https://github.com/Alluxio/alluxio/issues/17341)). Now we want to find whether this bug affect Fluid.

**What you expect to happen:**
If this bug in Alluxio does affect Fluid, the secondary copy command in application pod will be slow when using Alluxio 2.9.0 but will be fast when using Alluxio 2.8.1.

**How to reproduce it**
1. Create a Dataset and AlluxioRuntime
2. Create a application pod to bound this Dataset
3. Copy file in the application pod
4. Delete the application pod and re-create it.
5. Copy file in the application pod again.
6. If the secondary copy command is slow in Alluxio 2.9.0 but is fast in Alluxio 2.8.1, we can say this Alluxio bug does affects Fluid.

**Additional Information**
Here is my test result.

**Test Case 1**
- Version: Alluxio 2.9.0
- Scenario: Accelerate WebUFS
- Configuration of Dataset, Runtime and Application:
```yaml
# Dataset
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: alluxio-demo
spec:
  mounts:
    - mountPoint: https://mirrors.bit.edu.cn/apache/spark/
      name: spark
---
# Runtime
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: alluxio-demo
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: "0.95"
        low: "0.7"
---
# Application
apiVersion: v1
kind: Pod
metadata:
  name: alluxio-demo-app
spec:
  containers:
    - name: alluxio-demo-app
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: alluxio-demo
  nodeSelector:
    kubernetes.io/hostname: promote.ldns.rate.local
  volumes:
    - name: alluxio-demo
      persistentVolumeClaim:
        claimName: alluxio-demo
```
- Result
![dev-2 9 0-fluid](https://user-images.githubusercontent.com/63225111/236727005-a07059f2-76f8-44a2-b1d7-eacf3024a01b.png)

**Test Case 2**
- Version: Alluxio 2.8.1
- Scenario: Accelerate WebUFS
- Configuration of Dataset, Runtime and Application:
```yaml
# Dataset and Application configuration are same as Test Case 1
# Runtime
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: alluxio-demo
spec:
  alluxioVersion:
    imageTag: 2.8.1
  fuse:
    imageTag: 2.8.1
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: "0.95"
        low: "0.7"
```
- Result
![dev-2 8 1-fluid](https://user-images.githubusercontent.com/63225111/236727395-d48cc253-739b-42d3-8c89-d206ca22235b.png)

**Test Case 3**
- Version: Alluxio 2.9.0
- Scenario: Accelerate Minio
- Configuration of Dataset, Runtime and Application:
```yaml
# Dataset
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: minio-bucket
spec:
  mounts:
    - mountPoint: s3://fluid-test
      name: miniobucket
      options:
        alluxio.underfs.s3.endpoint: http://114.212.84.87:9000
        alluxio.underfs.s3.disable.dns.buckets: "true"
        alluxio.underfs.s3.disable.inherit.acl: "false"
      encryptOptions:
        - name: aws.accessKeyId
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: aws.accessKeyId
        - name: aws.secretKey
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: aws.secretKey
---
# Runtime
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime 
metadata:
  name: minio-bucket
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10G
        high: "0.95"
        low: "0.7"
---
# Application
apiVersion: v1
kind: Pod
metadata:
  name: data-read-job
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: minio-test
  nodeSelector:
    kubernetes.io/hostname: promote.ldns.rate.local
  volumes:
    - name: minio-test
      persistentVolumeClaim:
        claimName: minio-bucket
```
- Result
![dev-2 9 0-fluid-minio](https://user-images.githubusercontent.com/63225111/236727703-dd2b80da-55b7-4d8b-8aed-44a3f46d173a.png)

**Test Case 4**
- Version: Alluxio 2.8.1
- Scenario: Accelerate Minio
- Configuration of Dataset, Runtime and Application:
```yaml
# Dataset and Application configuration are same as Test Case 3
# Runtime
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime 
metadata:
  name: minio-bucket
spec:
  alluxioVersion:
    imageTag: 2.8.1
  fuse:
    imageTag: 2.8.1
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10G
        high: "0.95"
        low: "0.7"
```
- Result
![dev-2 8 1-fluid-minio](https://user-images.githubusercontent.com/63225111/236727905-b69e6dea-0ece-4c7f-a1af-a0ade4a0326e.png)

**Conclusion**
1. In all test cases, the secondary copy command is fast.
2. In test case 1 and 2, when Dataset bound WebUFS, the first copy command when using Alluxio 2.9.0 is ***much slower*** than using Alluxio 2.8.1.
