### ISSUE TITLE
[BUG] JindoRuntime's FUSE sidecar failed to start

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#3242]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

For example, given a common dataset and jindoruntime. Create a pod with the following spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    serverless.fluid.io/inject: "true"
spec:
  containers:
    - name: nginx
      image: nginx
      command:
      - "bash"
      - "-c"
      - "sleep inf"
      volumeMounts:
        - mountPath: /data
          name: data-vol
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: demo-dataset
```
where `claimName: demo-dataset` is the name of the JindoRuntime.

The pod will crash with following error messages in the events:
```
Warning  FailedPostStartHook  0s    kubelet            Exec lifecycle hook ([bash -c time /check-mount.sh /jfs/jindofs-fuse jindo  >> /proc/1/fd/1]) for Container "fluid-fuse-0" in Pod "nginx_default(ec97b179-b359-4645-ab6b-e6259cf5510c)" failed - error: command 'bash -c time /check-mount.sh /jfs/jindofs-fuse jindo  >> /proc/1/fd/1' exited with 2: + ConditionPathIsMountPoint=/jfs/jindofs-fuse
+ MountType=jindo
+ SubPath=
+ count=0
+ cat /proc/self/mountinfo
+ grep /jfs/jindofs-fuse
+ grep jindo
+ sleep 3
++ expr 0 + 1
+ count=1
+ test 1 -eq 10
+ cat /proc/self/mountinfo
+ grep /jfs/jindofs-fuse
+ grep jindo
+ '[' '!' -e '/jfs/jindofs-fuse/*/' ']'
+ echo 'sub path [] not exist!'
+ exit 2

real  0m3.332s
user  0m0.005s
sys   0m0.007s
, message: "+ ConditionPathIsMountPoint=/jfs/jindofs-fuse\n+ MountType=jindo\n+ SubPath=\n+ count=0\n+ cat /proc/self/mountinfo\n+ grep /jfs/jindofs-fuse\n+ grep jindo\n+ sleep 3\n++ expr 0 + 1\n+ count=1\n+ test 1 -eq 10\n+ cat /proc/self/mountinfo\n+ grep /jfs/jindofs-fuse\n+ grep jindo\n+ '[' '!' -e '/jfs/jindofs-fuse/*/' ']'\n+ echo 'sub path [] not exist!'\n+ exit 2\n\nreal\t0m3.332s\nuser\t0m0.005s\nsys\t0m0.007s\n"
  Normal   Killing            0s  kubelet  FailedPostStartHook
  Warning  FailedPreStopHook  0s  kubelet  Exec lifecycle hook ([/prestop.sh]) for Container "fluid-fuse-0" in Pod "nginx_default(ec97b179-b359-4645-ab6b-e6259cf5510c)" failed - error: command '/prestop.sh' exited with 137: , message: "excute jindofs-fuse umount\nFLUID_FUSE_MOUNTPOINT = /jfs/jindofs-fuse\n"
  Normal   Pulling            0s  kubelet  Pulling image "nginx"
```

**What you expect to happen:**
Pod should launch with no error.

**How to reproduce it**

**Additional Information**
