### ISSUE TITLE
[BUG]Dataset数据不同步到后端存储

### ISSUE THREAD

**Issue by BussanQ** [fluid-cloudnative/fluid#3260]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s1.22.17 
fluid 0.8.5 

**Describe the bug**
配置dataset

```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: imagenetf
spec:
  mounts:
  - mountPoint: oss://dir
    name: imagenetf
    path: /
    options:
      fs.oss.accessKeyId: ak
      fs.oss.accessKeySecret: sk
      fs.oss.endpoint: 
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hostname
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: imagenetf
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10Gi
        high: "0.99"
        low: "0.8"
```
pod挂载pvc后，新建文件不会上传到oss，alluxio.user.file.writetype.default默认配置为MUST_CACHE

**What you expect to happen:**
ReadWriteMany默认情况下应该写入后端存储
