### ISSUE TITLE
[BUG] Failed to setup ddc engine due to error failed to install kubernetes resources of /charts/juicefs

### ISSUE THREAD

**Issue by so2bin** [fluid-cloudnative/fluid#3369]
**What is your environment(Kubernetes version, Fluid version, etc.)**
* kubeversion
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```
* fluid version
```
~$ helm list -n fluid-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
fluid   fluid-system    1               2023-07-23 21:04:58.608441171 +0800 CST deployed        fluid-0.9.1     0.9.1-e79e93b
```

**Describe the bug**
* I have create a dataset like this:
```yaml
# dataset
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  labels:
    app: hbb-demo-34-v0
  name: atms-mmt-hbb-demo-34-v0-2
  namespace: tmp-hbb-5
spec:
  mounts:
  - encryptOptions:
    - name: token
      valueFrom:
        secretKeyRef:
          key: token
          name: atms-juicefs-secret
    - name: access-key
      valueFrom:
        secretKeyRef:
          key: access-key
          name: atms-juicefs-secret
    - name: secret-key
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: atms-juicefs-secret
    mountPoint: juicefs:///atms/demo
    name: |
      hbb-demo-wps
    readOnly: true
  placement: Shared

# juicefsruntime
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  name: atms-mmt-hbb-demo-34-v0-2
  namespace: tmp-hbb-5
spec:
  replicas: 1
  tieredstore:
    levels:
    - high: "0.99"
      low: "0.1"
      mediumtype: MEM
      path: /var/lib/jfs/cache2/mem/3be8a8d366ee21b1041ebe2a27435d35
      quota: 50Gi
      volumeSource: {}
      volumeType: hostPath
    - high: "0.99"
      low: "0.1"
      mediumtype: SSD
      path: /var/lib/jfs/cache2/ssd/3be8a8d366ee21b1041ebe2a27435d35
      quota: 50Gi
      volumeSource: {}
      volumeType: hostPath
```

* It works correctly on the last week, but i got the follow error event today:
```
20s         Warning   ErrorProcessRuntime            juicefsruntime/atms-mmt-hbb-demo-34-v0-2          Failed to setup ddc engine due to error failed to install kubernetes resources of /charts/juicefs
```
* The juicefsruntime-controller got these error logs:
```
2023-07-31T15:55:54.638+0800    ERROR   juicefsctl.JuiceFSRuntime.reconcileRuntime      controllers/runtime_controller.go:164   Failed to setup the ddc engine  {"juicefsruntime": "tmp-hbb-5/atms-mmt-hbb-demo-35-v0-3", "error": "failed to install kubernetes resources of /charts/juicefs"}
github.com/fluid-cloudnative/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileInternal
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/runtime_controller.go:164
github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs.(*JuiceFSRuntimeReconciler).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go:120
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2023-07-31T15:55:55.536+0800    INFO    helm    helm/utils.go:62        Error: INSTALLATION FAILED: YAML parse error on juicefs/templates/fuse/daemonset.yaml: error converting YAML to JSON: yaml: line 18: did not find expected key

2023-07-31T15:55:55.537+0800    ERROR   helm    helm/utils.go:65        failed to execute InstallRelease() command      {"command": "/usr/local/bin/ddc-helm install -f /tmp/atms-mmt-hbb-demo-34-v0-2-juicefs-values.yaml1545390462 --namespace tmp-hbb-5 atms-mmt-hbb-demo-34-v0-2 /charts/juicefs", "error": "exit status 1"}
github.com/fluid-cloudnative/fluid/pkg/utils/helm.InstallRelease
        /go/src/github.com/fluid-cloudnative/fluid/pkg/utils/helm/utils.go:65
github.com/fluid-cloudnative/fluid/pkg/ddc/juicefs.(*JuiceFSEngine).setupMasterInternal
        /go/src/github.com/fluid-cloudnative/fluid/pkg/ddc/juicefs/master_internal.go:60
github.com/fluid-cloudnative/fluid/pkg/ddc/juicefs.JuiceFSEngine.SetupMaster
        /go/src/github.com/fluid-cloudnative/fluid/pkg/ddc/juicefs/master.go:61
github.com/fluid-cloudnative/fluid/pkg/ddc/base.(*TemplateEngine).Setup
        /go/src/github.com/fluid-cloudnative/fluid/pkg/ddc/base/setup.go:47
github.com/fluid-cloudnative/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileRuntime
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/runtime_controller.go:245
github.com/fluid-cloudnative/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileInternal
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/runtime_controller.go:164
github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs.(*JuiceFSRuntimeReconciler).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go:120
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
2023-07-31T15:55:56.051+0800    ERROR   juicefsctl.JuiceFSRuntime       controllers/runtime_controller.go:245   SetupMaster     {"juicefsruntime": "tmp-hbb-5/atms-mmt-hbb-demo-34-v0-2", "engine": "juicefs", "id": "tmp-hbb-5-atms-mmt-hbb-demo-34-v0-2", "error": "failed to install kubernetes resources of /charts/juicefs"}
github.com/fluid-cloudnative/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileRuntime
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/runtime_controller.go:245
github.com/fluid-cloudnative/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileInternal
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/runtime_controller.go:164
github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs.(*JuiceFSRuntimeReconciler).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/pkg/controllers/v1alpha1/juicefs/juicefsruntime_controller.go:120
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/src/github.com/fluid-cloudnative/fluid/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
```

**What you expect to happen:**

**How to reproduce it**
* I have no idea why this happens.

**Additional Information**
