### ISSUE TITLE
[BUG][AlluxioRuntime]Metadata not update when add/remove mountPoint in dataset

### ISSUE THREAD

**Issue by xliuqq** [fluid-cloudnative/fluid#3377]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s 1.21.5
fluid v0.9.0 branch

**Describe the bug**
For AlluxioRuntime, metadata(UFS TOTAL SIZE etc.) will not update when add/remove web mountPoint in dataset.

**What you expect to happen:**
Dataset metadata should be updated.

**How to reproduce it**
- create dataset and alluxio runtime with yaml below.
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: phy
spec:
  mounts:
    - mountPoint: https://mirrors.bit.edu.cn/apache/spark
      name: spark
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: phy
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 1Gi
        high: "0.95"
        low: "0.7"
```
- wait for dataset bound, get dataset show its `UFS Total Size` etc. metadata.
- patch dataset with adding another mountPoint `https://mirrors.bit.edu.cn/apache/flink/`
- wait for dataset status showing mounting two mountPoints
- get dataset show `UFS Total Size` is not changed.

**Additional Information**
[the metadata updating code](https://github.com/fluid-cloudnative/fluid/blob/b5ee92a1d3a83ed9ffbe5a4b7309e7c563333ed5/pkg/ddc/alluxio/ufs_internal.go#L212) return error if dataset has been modified, resulting in succeed mount with wrong metadata.
