### ISSUE TITLE
[BUG][AlluxioRuntime] multiple mountPoint containing root path is not correct mounted in alluxio

### ISSUE THREAD

**Issue by xliuqq** [fluid-cloudnative/fluid#3379]
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s 1.21, fluid 0.9

**Describe the bug**
multiple mountPoint containing root path '/' is not correct mounted in alluxio.
- create dataset and runtime using below yaml
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: phy
spec:
  mounts:
    - mountPoint: https://mirrors.bit.edu.cn/apache/spark/
      name: spark
    - mountPoint: https://mirrors.bit.edu.cn/apache/flink/
      path: /
      name: flink
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: phy
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 1Gi
        high: "0.95"
        low: "0.7"
```

execute `alluxio fs mount` command in master pod, output is 
```
https://mirrors.bit.edu.cn/apache/spark  on  /spark  (web, capacity=-1B, used=-1B, read-only, not shared, properties={test.name=xliu1992})
/underFSStorage                          on  /       (local, capacity=0B, used=0B, not read-only, not shared, properties={})

```
**What you expect to happen:**
the root path should mount on `https://mirrors.bit.edu.cn/apache/flink/` not `/`.

**Additional Information**
[related code](https://github.com/fluid-cloudnative/fluid/blob/9a2aa52822202ef775bde11069fff29ed46de238/pkg/utils/ufs_path_builder.go#L57) ignores root path mount when have multiple mountPoints.
