### ISSUE TITLE
[FEATURES] The Fluid webhook allows for modifying the mountRoot in the values.yaml of the Fluid chart for sidecar mode. For example, it can change the value of mountRoot from /runtime-mnt to /opt/runtime-mnt.

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#3406]
**What feature you'd like to add:**

The Fluid webhook allows for modifying the mountRoot in the values.yaml of the Fluid chart for sidecar mode. For example, it can change the value of mountRoot from `/runtime-mnt` to `/opt/runtime-mnt`.

**Why is this feature needed:**

**Comment by cheyang** [comment]
I also suggest validating if there are any negative impacts, such as upgrading the Fluid scenario where the old mountRoot becomes the new mountRoot. What will be the impact on existing datasets?

**Comment by zhang-x-z** [comment]
#### Test Background & Objective
Now, Fluid can start the Fuse in two mode: csi plugin and sidecar. The root mount path is defined in the `values.yaml` of Fluid Chart like below:
```yaml
...
runtime:
  ...
  mountRoot: /runtime-mnt
...
```
But in some cloud vendors, the root path `/runtime-mnt` is not writable. So users need to change the `mountRoot`. There are two ways to change this configuration:
1. Set the `mountRoot` when installing Fluid:
```bash
helm install fluid --set runtime.mountRoot=<user's root mount path> fluid/fluid
```
2. Upgrade installed Fluid with new `mountRoot`:
```bash
helm upgrade fluid --set runtime.mountRoot=<user's root mount path> fluid/fluid
```
In this test, we want to validate that changing this configuration is effective for sidecar mode.

#### Test Environment & configuration
1. Fluid: 0.9.1
2. K8s: 1.22.4
3. Dataset & Runtime (Alluxio Runtime and Minio UFS)
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: test-dataset 
spec:
  mounts:
    - mountPoint: s3://zxz-test
      name: test-dataset 
      options:
        alluxio.underfs.s3.endpoint: http://<my-ip>:<my-port>
        alluxio.underfs.s3.disable.dns.buckets: "true"
        alluxio.underfs.s3.disable.inherit.acl: "false"
      encryptOptions:
        - name: aws.accessKeyId
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: aws.accessKeyId
        - name: aws.secretKey
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: aws.secretKey
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime 
metadata:
  name: test-dataset
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10G
        high: "0.99"
        low: "0.8"
```
4. Test Job
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-sidecar-job
spec:
  template:
    metadata:
      labels:
        serverless.fluid.io/inject: "true"
    spec:
      containers:
        - name: demo
          image: busybox
          args:
            - -c
            - sleep 300; echo $(date -u) >> /out.txt
          command:
            - /bin/sh
          volumeMounts:
            - mountPath: /data
              name: demo
      restartPolicy: Never
      volumes:
        - name: demo
          persistentVolumeClaim:
            claimName: test-dataset
  backoffLimit: 4
```

#### Test Case 1: Install Fluid with new `mountRoot`

1. Install Fluid with new configuration `/opt/runtime-mnt`:
<img width="689" alt="1-1" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/0e1e950d-8248-423d-960a-1c3dc69011be">

2. Create test Dataset and Runtime:
<img width="602" alt="1-2" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/fe0b82a9-0162-4185-b3da-59885892e958">

3. Create test job:
<img width="449" alt="1-3" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/6e94cbbd-5dfa-48ad-9e0f-391a04866faa">

4. Check the root mount path:
<img width="809" alt="1-4" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/e52acbd3-8d71-4e12-866f-0565dda91a75">

We can see the root mount path is the new configuration: `mountRoot: /opt/runtime-mnt`.

#### Test Case 2: Upgrade Fluid with new configuration when there still exist some Datasets

1. Install Fluid with default `mountRoot`:
<img width="406" alt="2-1" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/fab4fa70-5728-47d3-894c-17c5caac9de5">

2. Create Dataset and Runtime:
<img width="611" alt="2-2" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/d23cf38a-ce02-4baf-9cd1-ab1365068cfc">

3. Check default root mount path:
<img width="781" alt="2-3" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/535d4a98-6e79-40ee-b233-855dc52e1592">

We can see the root mount path is the default configuration: `mountRoot: /runtime-mnt`

4. Upgrade Fluid with new `mountRoot`:
<img width="663" alt="2-4" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/9d143013-df6e-412b-8a8b-43aa9692837d">

5. Check the root mount path of the previous created Dataset:
<img width="783" alt="2-5" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/0bbe750a-e87a-4c4a-9f02-e7603154e0a4">

We can see the root mount path is still the default configuration: `mountRoot: /runtime-mnt`.

#### Test Case 3: Upgrade Fluid with new configuration then create new Dataset

1. Install Fluid with default `mountRoot`:
<img width="401" alt="3-1" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/b3c4c225-ddd0-4a6f-a931-6cc6cf16b521">

2. Upgrade Fluid with new `mountRoot`:
<img width="666" alt="3-2" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/03c31506-87c3-4475-839a-ee023c3b47f5">

3. Create Dataset and Runtime:
<img width="584" alt="3-3" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/1ba28635-6e1d-4a2f-bcb5-bda596bd6379">

4. Check the root mount path:
<img width="806" alt="3-4" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/d0361ee6-27b1-40c5-839f-cf601df885c3">

We can see the root mount path is the new configuration: `mountRoot: /opt/runtime-mnt`

#### Test Case 4: Upgrade Fluid with new configuration when there are some Jobs are using Datasets.

1. Install Fluid with default `mountRoot`:
<img width="406" alt="4-1" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/e3a6d821-ce2e-405f-aa47-76d91e0b7b9c">

2. Create Dataset and Runtime:
<img width="590" alt="4-2" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/fb2f7a00-b28e-42e4-a26d-b7fd9b86bc2c">

3. Create test job:
<img width="447" alt="4-3" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/12639502-5377-4d30-9785-31f846f2005b">

4. Upgrade Fluid with new `mountRoot` while test job is running:
<img width="667" alt="4-4" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/137da499-4a13-4116-8779-18054f2621a2">

5. Check the root mount path:
<img width="790" alt="4-5" src="https://github.com/fluid-cloudnative/fluid/assets/63225111/0ac0b9cd-a8d5-447d-aae7-3a6a78bea7c4">

We can see the root mount path is still the default configuration: `mountRoot: /runtime-mnt`
