### ISSUE TITLE
[FEATURES]Why Dataset with juicefs only support one mount?

### ISSUE THREAD

**Issue by so2bin** [fluid-cloudnative/fluid#3442]
**Description**
* From the description in this document: https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/juicefs/juicefs_runtime.md 
```
JuiceFS 对应的 Dataset 只支持一个 mount，且 JuiceFS 没有 UFS，mountPoint 中可以指定需要挂载的子目录（juicefs:/// 为根路径），会作为根目录挂载到容器内。
```
The mount number is limited to one, that is inconceivable.

**What feature you'd like to add:**
I want to create a `Dataset` with multiple mount points, like this example:
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  labels:
    app: hbb-demo-45-v1
  name: mmt-hbb-demo-45-v1-2
  namespace: tmp-empty-0
spec:
  mounts:
  - encryptOptions:
    - name: token
      valueFrom:
        secretKeyRef:
          key: token
          name: juicefs-secret
    - name: access-key
      valueFrom:
        secretKeyRef:
          key: access-key
          name: juicefs-secret
    - name: secret-key
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: juicefs-secret
    mountPoint: juicefs:///atms/demo
    name: hbb-demo
    readOnly: true
  - encryptOptions:
    - name: token
      valueFrom:
        secretKeyRef:
          key: token
          name: juicefs-secret
    - name: access-key
      valueFrom:
        secretKeyRef:
          key: access-key
          name: juicefs-secret
    - name: secret-key
      valueFrom:
        secretKeyRef:
          key: secret-key
          name: juicefs-secret
    mountPoint: juicefs:///atms/vol-2
    name: hbb-demo
    readOnly: true
  placement: Shared
```
But in the reality is that fluid only create one PVC for me:
```
~/test/fluid$ kubectl get pvc -n tmp-empty-0  | grep hbb-demo-45-v1
mmt-hbb-demo-45-v1-3        Bound    tmp-empty-0-mmt-hbb-demo-45-v1-3        100Pi      ROX            fluid          47m
```
And a pod mounting this PVC can only access the data in the second mount point:` juicefs:///atms/vol-2`

**Why is this feature needed:**
* Can `Dataset` support multiple mountpoints with juicefs?
* Or is there any other way to reach this target?
