### ISSUE TITLE
[BUG] JindoRuntime worker's annotation for pod spec overwrites master's

### ISSUE THREAD

**Issue by David-Xiang** [fluid-cloudnative/fluid#3623]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Kubernetes version: 1.26.3 (Aliyun ASK)
Fluid version: 1.0.5

**Describe the bug**
The master pod of JindoRuntime is started on a node with the spec of the worker's. It seems that the worker's annotation for pod spec overwrites master's.

**How to reproduce it**
use below yaml for JindoRuntime
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: jindo-dataset
spec:
  replicas: 3
  master:
    podMetadata:
      annotations:
        k8s.aliyun.com/eci-use-specs: ecs.g7ne.xlarge
        k8s.aliyun.com/eci-image-cache: "true"
  worker:
    podMetadata:
      annotations:
        k8s.aliyun.com/eci-use-specs: ecs.g7ne.2xlarge
        k8s.aliyun.com/eci-image-cache: "true"
  tieredstore:
    levels:
      - mediumtype: MEM
        volumeType: emptyDir
        path: /dev/shm
        quota: 32Gi
        high: "0.99"
        low: "0.99"
```
