### ISSUE TITLE
[BUG] local options affects sharedOptions defined in Dataset.spec.mounts when using ThinRuntime

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#4252]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid master version.

**Describe the bug**
When trying to mount multiple mount points within one Dataset, there are two levels of options for different mount points: mountpoint-level options(i.e. Dataset.spec.mounts[*].options) and dataset-level options (i.e. Dataset.spec.sharedOptions). 

mountpoint-level options are defined in each `Dataset.spec.mounts[*]` so they should override the `Dataset.spec.sharedOptions`. However, mountpoint-level options affect options defined in other mounts which is not expected.

For instance like:
```
kind: Dataset
spec:
  sharedOptions:
    foo: bar1
  mounts:
  - mountPoint: test1
    name: test1
    path: /test1
  - mountPoint: test2
    name: test2
    path: /test2
    options:
      foo: bar2
```

So the options for "test1" should be `foo=bar1` and the options for "test2" should be `foo=bar2`. However, the configmap looks like:

```
apiVersion: v1
data:
  config.json: '{"mounts":[{"mountPoint":"test1","options":{"foo":"bar2"},"name":"test1","path":"/test1"},{"mountPoint":"test2","options":{"foo":"bar2"},"name":"test2","path":"/test2"}],"targetPath":"/runtime-mnt/thin/default/test/thin-fuse","accessModes":["ReadOnlyMany"]}'
kind: ConfigMap
```
where options for both "test1" and "test2" are `foo=bar2`.

**What you expect to happen:**
mountpoint-level options should not affect options defined in `Dataset.spec.sharedOptions`

**How to reproduce it**

**Additional Information**
