### ISSUE TITLE
[BUG] Incorrect UFS total size when setting `spec.mounts[].path` with JindoRuntime

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#4273]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid v1.0.1

**Describe the bug**
The Dataset bound with JindoRuntime shows "0.00B" UFS Total size, but UFS is not empty.
```
NAME    UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
demo2   0.00B            0.00B    2.00GiB          0.0%                Bound   107s
```

This bug occurs when explicitly setting `Dataset.spec.mounts[*].path` to a non-root path, for example:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: demo2
spec:
  placement: Shared
  accessModes:
  - ReadOnlyMany
  mounts:
      mountPoint: <mountPoint>
      name: demo2
      path: /mybucket
```

**What you expect to happen:**
`Dataset.Status.UfsTotalSize` should be calculated properly.

**How to reproduce it**
1. create a dataset with `spec.mounts[*].path`
2. create a JindoRuntime, and bind it to the dataset.

**Additional Information**
