### ISSUE TITLE
[BUG]JindoRuntime cannot access s3

### ISSUE THREAD

**Issue by hualongfeng** [fluid-cloudnative/fluid#4430]
**What is your environment(Kubernetes version, Fluid version, etc.)**
```
~/ai/opea/chatqna# kubectl get node
NAME               STATUS   ROLES           AGE    VERSION
icelake-server-2   Ready    control-plane   19d    v1.29.9
opea-dev10         Ready    <none>          5d2h   v1.29.9
~/ai/opea/chatqna# kubectl version
Client Version: v1.29.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.9
~/ai/opea/chatqna# helm list
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION  
fluid	default  	1       	2024-11-15 13:53:02.904415378 +0800 CST	deployed	fluid-1.0.3	1.0.3-ccdf3a9
root@icelake-server-2:~/ai/opea/chatqna# sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
root@opea-dev10:~# sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```
**Describe the bug**

I access s3 using JindoRuntime failed.

**What you expect to happen:**
access s3 using JindoRuntime succeed and can show the s3 objects on mounting directory
**How to reproduce it**
```
root@icelake-server-2:~/ai/opea/chatqna# cat fluid_opea_s3_only_read_chat_7b_jindo.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "MDU1NWIzNTY1NGFkMTY1NmQ4MDQ="  # echo -n '{access_key}' | base64
  AWS_SECRET_ACCESS_KEY: "aDdHaHh1QkxUcmxoVlV5eFNQVUtVVjhyLzJFSTRuZ3FKeEQ3aUJkQllMaHdsdU4zMEphVDNRPT0="   # echo -n '{secret_key}' | base64
---

---
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: opea-models
spec:
  mounts:
    - mountPoint: s3://192.168.0.62:8000
      name: models--Intel--neural-chat-7b-v3-3
      encryptOptions:
      - name: fs.s3.accessKeyId
        valueFrom:
          secretKeyRef:
            name: s3-secret
            key: AWS_ACCESS_KEY_ID
      - name: fs.s3.accessKeySecret
        valueFrom:
          secretKeyRef:
            name: s3-secret
            key: AWS_SECRET_ACCESS_KEY
  accessModes:
    - ReadOnlyMany
---
---
# runtime
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: opea-models
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 50Gi
        high: "0.95"
        low: "0.7"
---

```
**Additional Information**
I can access s3 by s3cmd, this is config(.s3cfg):
```
[default]
access_key = 0555b35654ad1656d804
host_base = 192.168.0.62:8000
host_bucket = no.way.in.hell
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
use_https = False

```
pv,pvc show normally.
```
root@icelake-server-2:~/ai/opea/chatqna# kubectl get pv,pvc
NAME                                   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/default-opea-models   100Pi      ROX            Retain           Bound    default/opea-models   fluid          <unset>                          12m

NAME                                STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/opea-models   Bound    default-opea-models   100Pi      ROX            fluid          <unset>                 12m
root@icelake-server-2:~/ai/opea/chatqna# vim fluid_opea_s3_only_read_chat_7b_jindo.yaml

```

**Comment by hualongfeng** [comment]
Hi @plusplusjiajia  https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/3.x/jindo_fluid/Current/jindo_fluid_s3_ufs_example.md This example doesn't work. Please help check it again.

**Comment by cheyang** [comment]
@hualongfeng can you check this sample？ Thanks

**Comment by hualongfeng** [comment]
Hi @cheyang   It worked by reference https://github.com/kserve/kserve/blob/master/docs/samples/fluid/jindo.yaml。 Thanks

Here is my current yaml file that works, for future reference:
And `curl -I http://opea-models.xcc-server2.sh.intel.com:8000/` can access s3.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "MDU1NWIzNTY1NGFkMTY1NmQ4MDQ="  # echo -n '{access_key}' | base64
  AWS_SECRET_ACCESS_KEY: "aDdHaHh1QkxUcmxoVlV5eFNQVUtVVjhyLzJFSTRuZ3FKeEQ3aUJkQllMaHdsdU4zMEphVDNRPT0="   # echo -n '{secret_key}' | base64
---

---
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: opea-models
spec:
  mounts:
    - mountPoint: s3://opea-models/models--Intel--neural-chat-7b-v3-3
      name: models--Intel--neural-chat-7b-v3-3
      options:
        fs.s3.endpoint: xcc-server2.sh.intel.com:8000
        fs.s3.usehttps: "0"
        fs.s3.useanoncredential: "false"
      encryptOptions:
      - name: fs.s3.accessKeyId
        valueFrom:
          secretKeyRef:
            name: s3-secret
            key: AWS_ACCESS_KEY_ID
      - name: fs.s3.accessKeySecret
        valueFrom:
          secretKeyRef:
            name: s3-secret
            key: AWS_SECRET_ACCESS_KEY
  accessModes:
    - ReadOnlyMany
---

---
# runtime
apiVersion: data.fluid.io/v1alpha1
kind: JindoRuntime
metadata:
  name: opea-models
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 50Gi
        high: "0.95"
        low: "0.7"
  fuse:
    properties:
      fs.jindofsx.data.cache.enable: "true"
      # performance optimization
      fs.jindofsx.stream.maxPendingBlocks: "200"
      fs.s3.download.queue.size: "16"
      fs.s3.download.thread.concurrency: "32"
      fs.s3.read.readahead.buffer.count: "16"
    args:
      - -okernel_cache
      - -oro
      - -oattr_timeout=7200
      - -oentry_timeout=7200
      - -ometrics_port=9089  
---

```
