### ISSUE TITLE
[FEATURES] Support creating Runtime without Dataset dependency

### ISSUE THREAD

**Issue by osswangxining** [fluid-cloudnative/fluid#4518]
**What feature you'd like to add:**

## Background
In some corner cases, users need to create Runtime without pre-defining a Dataset resource. Current Fluid architecture requires strict Dataset-Runtime binding, which brings unnecessary complexity for temporary data scenarios. we propose allowing creation of runtime without Dataset dependency through Kubernetes annotations.

```yaml
### Annotation Design
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  annotations:
    fluid.io/dataset-check-policy: "ignore"  # Core control flag, 
spec:
```

**Why is this feature needed:**
For some practical cases, users need to create Runtime without pre-defining a Dataset resource.

**Comment by cheyang** [comment]
> **What feature you'd like to add:**
> 
> ## Background
> In some corner cases, users need to create Runtime without pre-defining a Dataset resource. Current Fluid architecture requires strict Dataset-Runtime binding, which brings unnecessary complexity for temporary data scenarios. we propose allowing creation of runtime without Dataset dependency through Kubernetes annotations.
> 
> ### Annotation Design
> ```yaml
> apiVersion: data.fluid.io/v1alpha1
> kind: JuiceFSRuntime
> metadata:
>   annotations:
>     fluid.io/dataset-check-policy: "ignore"  # Core control flag, 
> spec:
> **Why is this feature needed:** For some practical cases, users need to create Runtime without pre-defining a Dataset resource.


Thank you for raising this proposal! 😊  

### **Our Recommendation**  
Instead of bypassing Dataset checks entirely, we propose an **`auto-create` policy** to automatically generate minimal but valid Datasets. This maintains compatibility with Fluid’s core features while streamlining your workflow:  

```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Runtime
metadata:
  annotations:
    fluid.io/dataset-policy: "auto-create"  # Auto-generates Dataset
spec:
  
```

**Why `auto-create` Over `none`:**  
1. **Future-Proof Compatibility**： Auto-created Datasets work seamlessly with DataLoad (preheating), DataMigrate, and Fluid’s monitoring stack.  
2. **Production-Ready**:  This model aligns with Fluid’s architecture, avoiding technical debt from diverging workflows.
