### ISSUE TITLE
[BUG] Unexpected "Cached Percentage`  when setting multi-tier cache store

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#539]
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid (https://github.com/fluid-cloudnative/fluid/commits/master)

**Describe the bug**
I created a dataset and an alluxioruntime like this:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: hbase
spec:
  mounts:
    - mountPoint: https://mirror.bit.edu.cn/apache/hbase/stable/
      name: hbase
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: hbase
spec:
  replicas: 2
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: "0.95"
        low: "0.7"
      - mediumtype: SSD
        path: /mnt/cache/cache1
        quota: 4Gi
        high: "0.95"
        low: "0.8"
  properties:
    alluxio.user.block.size.bytes.default: 256MB
    alluxio.user.streaming.reader.chunk.size.bytes: 256MB
    alluxio.user.local.reader.chunk.size.bytes: 256MB
    alluxio.worker.network.reader.buffer.size: 256MB
    alluxio.user.streaming.data.timeout: 300sec
  fuse:I think you can 
    args:
      - fuse
      - --fuse-opts=kernel_cache,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200,nonempty,max_readahead=0
```

After creation, I checked dataset status by `kubectl get dataset hbase`. For now, I haven't accessed or loaded any data from the dataset, so I expected to see no data is cached.  But I got the following unexpected result:
```
NAME    UFS TOTAL SIZE   CACHED    CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
hbase   544.30MiB        2.00GiB   6.00GiB          376.3%              Bound   102s
```

Then, by running `alluxio fs du -h /` in the alluxio-master Pod, I got this:
```
File Size     In Alluxio       Path
1093.92KB     0B (0%)          /hbase/CHANGES.md
645.94KB      0B (0%)          /hbase/RELEASENOTES.md
0B            0B (0%)          /hbase/api_compare_2.3.2_to_2.3.3RC1.html
259.37MB      0B (0%)          /hbase/hbase-2.3.3-bin.tar.gz
248.45MB      0B (0%)          /hbase/hbase-2.3.3-client-bin.tar.gz
34.78MB       0B (0%)          /hbase/hbase-2.3.3-src.tar.gz
```
It seems to me no data is cached in Alluxio. 

Finally, by running `alluxio fsadmin report capacity` in the alluxio-master Pod, I got this:
```
Capacity information for all workers: 
    Total Capacity: 6.00GB
        Tier: MEM  Size: 2048.00MB
        Tier: SSD  Size: 4096.00MB
    Used Capacity: 2048.00MB
        Tier: MEM  Size: 1024.00MB
        Tier: SSD  Size: 1024.00MB
    Used Percentage: 33%
    Free Percentage: 67%

Worker Name      Last Heartbeat   Storage       Total            MEM           SSD           
192.168.5.109    0                capacity      6.00GB           2048.00MB     4096.00MB     
                                  used          2048.00MB (33%)  1024.00MB     1024.00MB     
```
So, Alluxio did use some cache capacity.

**This problem only occurs when setting multi-tier cache store, so they're probably related.**

**What you expect to happen:**
No cache capacity should be used when no data cached in Alluxio.

**How to reproduce it**
I think the dataset and alluxioruntime yaml mentioned above is enough to reproduce it.

**Additional Information**
