### ISSUE TITLE
[FEATURES] Support preferred affinity for worker when fuse client in global mode

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#588]
**What feature you'd like to add:**

Currently, we have support the global mode for fuse client:  https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/fuse_affinity.md

But there is a scenario that:

We already have a dataset with fuse client in global deployment and node selectors.

```yaml
fuse:
    global: true
    nodeSelector:
      fuse: "true"
```

we'd like to scale out the workers. We prefer to schedule the worker pod to the node which already has node selectors.

**Why is this feature needed:**
