### ISSUE TITLE
[BUG] Dataload can`t full load data

### ISSUE THREAD

**Issue by xieydd** [fluid-cloudnative/fluid#633]
**What is your environment(Kubernetes version, Fluid version, etc.)**
version: 0.4.0
commit id: 51b6a44c3c6bcc1bc828aaaa6c020f2627bb0553
**Describe the bug**
When i ran dataload job completely, the dataset is not fully loaded.
```
apiVersion: data.fluid.io/v1alpha1
kind: DataLoad
metadata:
  name: slice1-dataload
spec:
  dataset:
    name: slice1
    namespace: default
  loadMetadata: true
  target:
    - path: /
      replicas: 1
```

```
slice1-dataload-loader-job-7rrpz   0/1     Completed   0          46m   10.16.0.166     10.16.100.234   <none>           1/1
NAME     UFS TOTAL SIZE   CACHED      CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
slice1   300.31GiB        171.93GiB   400.00GiB        57.3%               Bound   73m
```

This is dataload full log: 
[dataload.log](https://github.com/fluid-cloudnative/fluid/files/6136572/dataload.log)
