### ISSUE TITLE
[BUG] Support path to overwrite name in Dataset API

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#643]
**What feature you'd like to add:**

目前希望支持如果只有一个数据源的情况下，可以将该数据源mount到alluxio协议的根目录下。这样的好处是用户的程序完全无需改变。

```
  
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: hbase
spec:
  mounts:
    - mountPoint: oss://test
      name: hbase
      path: "/"
```

需要考虑的是

1.HDFS，OSS等协议的支持方式
2.PVC协议的支持方式

**Why is this feature needed:**
