### ISSUE TITLE
[BUG] rename nodeSelector to masterNodeSelector

### ISSUE THREAD

**Issue by cheyang** [fluid-cloudnative/fluid#796]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

Currently, we want to deploy master to specific node by using nodeSelector. I suggest to change it to masterNodeSelector which will not mislead the user.

```yaml
nodeSelector:
                  additionalProperties:
                    type: string
                  description: NodeSelector is a selector which must be true for the
                    master to fit on a node
                  type: object
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**
