### ISSUE TITLE
[BUG] Assignment to entry in nil map if no properties set in AlluxioRuntime

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#93]
**What is your environment(Kubernetes version, Fluid version, etc.)**
- Fluid 0.2.0
- Kubernetes 1.16.9
- Go 1.13.9
- Linux/amd64

**Descirbe the bug**

I've got a `assignment to entry in nil map` error if I set no properties in `runtime.yaml` like this:
```
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: hbase
spec:
  replicas: 2
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 2Gi
        high: "0.95"
        low: "0.7"
        storageType: Memory
#  properties:
#    alluxio.user.file.writetype.default: MUST_CACHE
#    alluxio.master.journal.folder: /journal
#    alluxio.master.journal.type: UFS
#    alluxio.user.block.size.bytes.default: 256MB
#    alluxio.user.streaming.reader.chunk.size.bytes: 256MB
#    alluxio.user.local.reader.chunk.size.bytes: 256MB
#    alluxio.worker.network.reader.buffer.size: 256MB
#    alluxio.user.streaming.data.timeout: 300sec
  master:
    jvmOptions:
      - "-Xmx4G"
  worker:
    jvmOptions:
      - "-Xmx4G"
  fuse:
    jvmOptions:
      - "-Xmx4G "
      - "-Xms4G "
    # For now, only support local
    shortCircuitPolicy: local
    args:
      - fuse
      - --fuse-opts=direct_io,ro,max_read=131072,attr_timeout=7200,entry_timeout=7200,nonempty

```

controller-manager will crash, and here's a snippet of controller-manager log:
```
E0829 14:21:24.519270       1 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 273 [running]:
github.com/cloudnativefluid/fluid/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14742a0, 0x17f7630)
	/go/src/github.com/cloudnativefluid/fluid/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/cloudnativefluid/fluid/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cloudnativefluid/fluid/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14742a0, 0x17f7630)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cloudnativefluid/fluid/pkg/ddc/alluxio.(*AlluxioEngine).transformCommonPart(0xc0005af8c0, 0xc000501400, 0xc000214900, 0xc0004800a0, 0xc000346280)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/alluxio/transform.go:106 +0x222
github.com/cloudnativefluid/fluid/pkg/ddc/alluxio.(*AlluxioEngine).transform(0xc0005af8c0, 0xc000501400, 0xc00038a3c0, 0x14, 0xc000607cf0)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/alluxio/transform.go:41 +0x82
github.com/cloudnativefluid/fluid/pkg/ddc/alluxio.(*AlluxioEngine).generateAlluxioValueFile(0xc0005af8c0, 0xc000501400, 0x0, 0x0, 0x8, 0xc0008b59e0)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/alluxio/master_internal.go:75 +0x107
github.com/cloudnativefluid/fluid/pkg/ddc/alluxio.(*AlluxioEngine).setupMasterInernal(0xc0005af8c0, 0x162c3cd, 0xb)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/alluxio/master_internal.go:43 +0xb2
github.com/cloudnativefluid/fluid/pkg/ddc/alluxio.(*AlluxioEngine).SetupMaster(0xc0005af8c0, 0x1635901, 0x0)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/alluxio/master.go:125 +0x584
github.com/cloudnativefluid/fluid/pkg/ddc/base.(*TemplateEngine).Setup(0xc000890000, 0x18479a0, 0xc000042150, 0xc000607cf0, 0x7, 0xc000607ce0, 0x5, 0x184e500, 0xc0001bec60, 0xc00034ca80, ...)
	/go/src/github.com/cloudnativefluid/fluid/pkg/ddc/base/setup.go:52 +0x750
github.com/cloudnativefluid/fluid/pkg/controllers.(*RuntimeReconciler).ReconcileRuntime(0xc0000455c0, 0x184e440, 0xc000890000, 0x18479a0, 0xc000042150, 0xc000607cf0, 0x7, 0xc000607ce0, 0x5, 0x184e500, ...)
	/go/src/github.com/cloudnativefluid/fluid/pkg/controllers/runtime_controller.go:195 +0x1ab
```
**What you expect to happen:**
Fluid runs properly, and Alluxio starts with default settings.

**How to reproduce it**
Create any `AlluxioRuntime` with no properties set is okay for me to reproduce this bug.

**Additional Information**
None
