### ISSUE TITLE
[FEATURES] Dataset nodeAffinity should support matchFields

### ISSUE THREAD

**Issue by TrafalgarZZZ** [fluid-cloudnative/fluid#991]
**What feature you'd like to add:**
For now, Fluid allow `nodeAffinity.required.nodeSelectorTerms[i].matchFields` to be defined in Dataset while it is ignored and takes no effect.

Dataset nodeAffinity should support matchFields like this:
```yaml
nodeAffinity:
  required:
    nodeSelectorTerms:
      - matchFields:
        - key: metadata.name
           operator: In
           values:
           - target-host-name
```

**Why is this feature needed:**
To make affinity fields of Dataset be consistent with affinity fields of Pods.

This is useful when users want to deploy Runtimes on some specific hosts.
