### ISSUE TITLE
mount with shared not working

### ISSUE THREAD

**Issue by mqyang56** [fluid-cloudnative/fluid#998]
**What is your environment(Kubernetes version, Fluid version, etc.)**
`kubernetes`: v1.18.13
`fluid`: 0.6.0
**Describe the bug**
mount with shared not working

**What you expect to happen:**
mount with shared succeed.

**How to reproduce it**
As shown below

**Additional Information**
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
...
spec:
  mounts:
  - mountPoint: pvc://datasets
    name: datasets
    shared: true
...
```
alluxio fs mount (exec command in worker container)
```
/underFSStorage  on  /  (local, capacity=499.76GB, used=260.49GB(52%), not read-only, not shared, properties={})
```

AlluxioRuntimeController partial logs:
```
alluxio/dataset.go:59	the dataset status	{"alluxioruntime": "gddi-vicuna/fluid-coding-datasets-cache", "status": {"mounts":[{"mountPoint":"pvc://datasets","name":"datasets","shared":true}],
```
